### ISSUE TITLE
PHP Fatal error when .bldr.yml is missing

### ISSUE THREAD

**Issue by ameenross** [bldr-io/bldr#137]
I'm getting this error when running `bldr` on a new project.
> PHP Fatal error:  Class 'Bldr\Exception\ConfigurationFileNotFoundException' not found in phar:///usr/bin/bldr/src/Config.php on line 85

After creating the `.bldr.yml` file this error disappeared.

**Comment by WouterJ** [comment]
@aequasi you removed it in 7.0.0, but didn't change the usage. Should the exception class be added again?

**Comment by aequasi** [comment]
Yeah, it should be... Idk why i removed it.
