### ISSUE TITLE
`bldr run` without profile argument should run the default profile

### ISSUE THREAD

**Issue by ameenross** [bldr-io/bldr#141]
Developers are lazy. Typing the extra "&lt;space&gt;default" behind `bldr run` feels cumbersome. Like other task runners, running the default profile should be what is intended by omitting the actual profile to be run.

**Comment by aequasi** [comment]
You know..... It USED to do that.... but then i kinda just removed "default" profiles. I can throw that back in.  

Fyi, you can also run it with `bldr default`

**Comment by ameenross** [comment]
Well, as `bldr run` is shorter and makes more sense than `bldr default`, I hope you will put it back in. :)
