### ISSUE TITLE
[Request] Drop need for 'run' command

### ISSUE THREAD

**Issue by tag** [bldr-io/bldr#147]
Was looking at the docs. I like where this is going, and am excited to see a PHP-based build system that's not XML dependent.

In keeping with other build systems, however, may I suggest that the "run" command be optional, or not used at all? With `ant`, `make`, and others, I just need the `ant clean` or `make clean`, whereas with bldr it seems I would need `bldr run clean`. Less friendly IMHO, and being consistent with other build tools might lessen any learning curve.

Wish you the best, and I'll keep my eye on this app!

**Comment by aequasi** [comment]
its already optional :)
