### ISSUE TITLE
PHP Tasks Extension

### ISSUE THREAD

**Issue by aequasi** [bldr-io/bldr#8]
Mentioned in #2 

This may not be the right name, but it would be nice to have methods for the tasks like:

* [ ] PHPUnit
* [ ] PHPCS
* [ ] PHPMD
* [ ] Behat
* [ ] PHPDox
* [ ] PHPCPD

**Comment by ameenross** [comment]
Let's re-open this. I would like to help creating such a block.

**Comment by aequasi** [comment]
Created https://github.com/bldr-io/php-block

**Comment by ameenross** [comment]
I suggest we implement tasks for the relevant projects listed here: http://phpqatools.org/
Additionally, I'd like to implement linting.

**Comment by aequasi** [comment]
:+1:

**Comment by ameenross** [comment]
I made issues over on https://github.com/bldr-io/php-block for the tasks we want. I think this can be closed.
